---
- name: "Copy from src to dist"
  copy:
    src: "~/artifact.tar.gz"
    dest: "~/artifact.tar.gz"

- name: "create new folder"
  shell: mkdir ~/backend

- name: "do unziping to copied files in dest backend"
  ansible.builtin.unarchive:
    src: ~/artifact.tar.gz
    dest: ~/backend
    
- name: "Install dependencies for project"
  shell: |
    cd ~/backend
    npm install
    npm i


- name: "sleep"
  shell: |
    sleep 15

- name: "Executing node"
  shell: |
    cd ~/backend
    pm2 stop default
    pm2 start npm -- start
  register: execute_node

- name: "execute node msg"
  debug:
    msg: "{{ execute_node.stdout_lines }}"