---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    
  environment:
      ENVIRONMENT: "{{ lookup('env','ENVIRONMENT') }}"
      TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
      TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
      TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
      TYPEORM_MIGRATIONS: "{{ lookup('env','TYPEORM_MIGRATIONS') }}"
      TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIES') }}"    
      API_URL: "{{ lookup('env','API_URL') }}"
    ansible_host_key_checking: false    
  
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:

    - name: "install python for Ansible."
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

  roles:
    - configure-prometheus-node-exporter
    - configure-server
    - deploy