---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 30 seconds for target connection to become reachable/usable."
      # Your code here
      wait_for_connection:
        timeout: 30

    - name: "install python for Ansible."
      # Your code here
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

  roles:
    # Your code here
    - configure-server
  #environment:
  #  TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
  #  TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
  #  TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
  #  TYPEORM_PORT: 5432
  #  TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
  #  TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
   # TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
  #  TYPEORM_MIGRATIONS: .src/migrations/*.ts
  