---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
      # Your code here

    - name: "install python for Ansible."
      become: true
      raw: test -e /usr/bin/python3 || (yum -y update && yum install -y python3)
      changed_when: false
      # Your code here

  roles:
    - configure-prometheus-node-exporter
    - configure-server
    # Your code here