---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  environment:
    - TYPEORM_MIGRATIONS: "{{ lookup('env','TYPEORM_MIGRATIONS') }}"
    - TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIES') }}"
    - TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    - TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    - TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
    - TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    - TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    - TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
    - ENVIRONMENT: "production"
  
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        delay: 5
        timeout: 600    #fix to 600

  
  #  - name: "install python for Ansible."
  #    # Your code here

  roles:
    # Your code here
    - configure-server