---

- name: "configuration play." 
  hosts: web
  user: ec2-user
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
  - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        delay: 1
        timeout: 600

    #- name: "install python for Ansible." // no need as it contains python
      # Your code here

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"  
    - TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"  
    - TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES')}}"  
    - TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"  
    - TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"  
    - TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"  
    - TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"  
    - TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT')}}"  
    - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"  

  roles:
    - configure-server