---

- name: "configuration play." 
  hosts: all
  user: ubuntu
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_host_key_checking: false
    ansible_stdout_callback: yaml
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    TYPEORM_MIGRATIONS: "{{ lookup('env','TYPEORM_MIGRATIONS') }}"
    TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIES') }}"
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
    ENVIRONMENT: "{{ lookup('env','ENVIRONMENT') }}"
    API_URL: "{{ lookup('env','API_URL') }}"

  gather_facts: true
  pre_tasks:
    - name: "wait 300 seconds for target connection to become reachable/usable."
      command: sleep 300s 

    - name: "install python for Ansible."
      become: true
      apt:
        name: python
        state: present
  roles:
    - deploy
