AWSTemplateFormatVersion: 2010-09-09

Description: >
  Cloudfront distribution for UdaPeople.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin Access Identity for Serverless Static Website

  WebpageCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub ${ID}.s3.amazonaws.com
            Id: webpage
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
        Enabled: True
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: False
          TargetOriginId: webpage
          ViewerProtocolPolicy: allow-all

Outputs:
  WorkflowID:
    Value: !Sub ${ID}
    Description: URL for website hosted on S3
    Export:
      Name: WorkflowID
  DistributionID:
    Value: !Ref WebpageCDN
    Export:
      Name: DistributionID
